import { Chain, ChainId } from "./types";

export const CHAINS: Chain[] = [
	{
		chainId: ChainId.ARBITRUM,
		chainAlias: "arbitrum",
		name: "Arbitrum One",
		networkType: "mainnet",
		rddUrl: "https://reference-data-directory.vercel.app/feeds-ethereum-mainnet-arbitrum-1.json",
		queryString: "arbitrum-mainnet",
		tags: ["streams", "smartData"],
	},
	{
		chainId: ChainId.ARBITRUM_SEPOLIA,
		chainAlias: "arbitrum-sepolia",
		name: "Arbitrum One Sepolia",
		networkType: "testnet",
		rddUrl: "https://reference-data-directory.vercel.app/feeds-ethereum-testnet-sepolia-arbitrum-1.json",
		queryString: "arbitrum-sepolia",
		tags: ["rates", "streams"],
	},
	{
		chainId: ChainId.AVALANCHE,
		chainAlias: "avalanche",
		name: "Avalanche",
		networkType: "mainnet",
		rddUrl: "https://reference-data-directory.vercel.app/feeds-avalanche-mainnet.json",
		queryString: "avalanche-mainnet",
		tags: ["smartData", "streams"],
	},
	{
		chainId: ChainId.AVALANCHE_FUJI,
		chainAlias: "avalanche-fuji",
		name: "Avalanche Fuji",
		networkType: "testnet",
		rddUrl: "https://reference-data-directory.vercel.app/feeds-avalanche-fuji-testnet.json",
		queryString: "avalanche-fuji",
		tags: ["smartData", "rates", "streams"],
	},
	{
		chainId: ChainId.BASE,
		chainAlias: "base",
		name: "Base",
		networkType: "mainnet",
		rddUrl: "https://reference-data-directory.vercel.app/feeds-ethereum-mainnet-base-1.json",
		queryString: "base-mainnet",
		tags: ["smartData"],
	},
	{
		chainId: ChainId.BASE_SEPOLIA,
		chainAlias: "base-sepolia",
		name: "Base Sepolia",
		networkType: "testnet",
		rddUrl: "https://reference-data-directory.vercel.app/feeds-ethereum-testnet-sepolia-base-1.json",
		queryString: "base-sepolia",
	},
	{
		chainId: ChainId.BNB,
		chainAlias: "bnb",
		name: "BNB Chain",
		networkType: "mainnet",
		rddUrl: "https://reference-data-directory.vercel.app/feeds-bsc-mainnet.json",
		queryString: "bnb-mainnet",
		tags: ["smartData"],
	},
	{
		chainId: ChainId.BNB_TESTNET,
		chainAlias: "bnb-testnet",
		name: "BNB Chain Testnet",
		networkType: "testnet",
		rddUrl: "https://reference-data-directory.vercel.app/feeds-bsc-testnet.json",
		queryString: "bnb-testnet",
	},
	{
		chainId: ChainId.ETHEREUM,
		chainAlias: "ethereum",
		name: "Ethereum",
		networkType: "mainnet",
		rddUrl: "https://reference-data-directory.vercel.app/feeds-mainnet.json",
		queryString: "ethereum-mainnet",
		tags: ["smartData"],
	},
	{
		chainId: ChainId.SEPOLIA,
		chainAlias: "sepolia",
		name: "Sepolia Testnet",
		networkType: "testnet",
		rddUrl: "https://reference-data-directory.vercel.app/feeds-ethereum-testnet-sepolia.json",
		queryString: "ethereum-sepolia",
		tags: ["rates"],
	},
	{
		chainId: ChainId.FANTOM,
		chainAlias: "fantom",
		name: "Fantom",
		networkType: "mainnet",
		rddUrl: "https://reference-data-directory.vercel.app/feeds-fantom-mainnet.json",
		queryString: "fantom-mainnet",
	},
	{
		chainId: ChainId.FANTOM_TESTNET,
		chainAlias: "fantom-testnet",
		name: "Fantom Testnet",
		networkType: "testnet",
		rddUrl: "https://reference-data-directory.vercel.app/feeds-fantom-testnet.json",
		queryString: "fantom-testnet",
	},
	{
		chainId: ChainId.LINEA,
		chainAlias: "linea",
		name: "Linea",
		networkType: "mainnet",
		rddUrl: "https://reference-data-directory.vercel.app/feeds-ethereum-mainnet-linea-1.json",
		queryString: "linea-mainnet",
	},
	{
		chainId: ChainId.OPTIMISM,
		chainAlias: "optimism",
		name: "Optimism",
		networkType: "mainnet",
		rddUrl: "https://reference-data-directory.vercel.app/feeds-ethereum-mainnet-optimism-1.json",
		queryString: "optimism-mainnet",
	},
	{
		chainId: ChainId.OPTIMISM_SEPOLIA,
		chainAlias: "optimism-sepolia",
		name: "Optimism Sepolia",
		networkType: "testnet",
		rddUrl: "https://reference-data-directory.vercel.app/feeds-ethereum-testnet-sepolia-optimism-1.json",
		queryString: "optimism-sepolia",
	},
	{
		chainId: ChainId.POLYGON,
		chainAlias: "polygon",
		name: "Polygon",
		networkType: "mainnet",
		rddUrl: "https://reference-data-directory.vercel.app/feeds-matic-mainnet.json",
		queryString: "polygon-mainnet",
		tags: ["smartData"],
	},
	{
		chainId: ChainId.POLYGON_AMOY,
		chainAlias: "polygon-amoy",
		name: "Polygon Amoy",
		networkType: "testnet",
		rddUrl: "https://reference-data-directory.vercel.app/feeds-polygon-testnet-amoy.json",
		queryString: "polygon-amoy",
		tags: ["smartData"],
	},
	{
		chainId: ChainId.SCROLL,
		chainAlias: "scroll",
		name: "Scroll",
		networkType: "mainnet",
		rddUrl: "https://reference-data-directory.vercel.app/feeds-ethereum-mainnet-scroll-1.json",
		queryString: "scroll-mainnet",
		tags: ["smartData"],
	},
	{
		chainId: ChainId.SCROLL_SEPOLIA,
		chainAlias: "scroll-sepolia",
		name: "Scroll Sepolia",
		networkType: "testnet",
		rddUrl: "https://reference-data-directory.vercel.app/feeds-ethereum-testnet-sepolia-scroll-1.json",
		queryString: "scroll-sepolia",
	},
	{
		chainId: ChainId.UNICHAIN_SEPOLIA,
		chainAlias: "unichain-sepolia",
		name: "Unichain Sepolia",
		networkType: "testnet",
		rddUrl: "https://reference-data-directory.vercel.app/feeds-ethereum-testnet-sepolia-unichain-1.json",
		queryString: "unichain-sepolia",
	},
];
