import { Chain } from "../types";

export enum ChainId {
	ETHEREUM = 1,
	SEPOLIA = 11155111,
	OPTIMISM = 10,
	OPTIMISM_SEPOLIA = 11155420,
	BNB = 56,
	BNB_TESTNET = 97,
	UNICHAIN = 130,
	UNICHAIN_SEPOLIA = 1301,
	POLYGON = 137,
	POLYGON_AMOY = 80002,
	BASE = 8453,
	BASE_SEPOLIA = 84532,
	ARBITRUM = 42161,
	ARBITRUM_SEPOLIA = 421614,
	AVALANCHE = 43114,
	AVALANCHE_FUJI = 43113,
	LINEA = 59144,
	LINEA_SEPOLIA = 59141,
	SCROLL = 534352,
	SCROLL_SEPOLIA = 534351,
}

export const CHAINS: Chain[] = [
	{
		chainId: ChainId.ETHEREUM,
		chainAlias: "ethereum",
		name: "Ethereum",
		networkType: "mainnet",
		explorerUrl: "https://etherscan.io",
		rddUrl: "https://reference-data-directory.vercel.app/feeds-mainnet.json",
		rpcUrl: {
			alchemy: "https://eth-mainnet.g.alchemy.com/v2/",
			infura: "https://mainnet.infura.io/v3/",
		},
	},
	{
		chainId: ChainId.SEPOLIA,
		chainAlias: "sepolia",
		name: "Sepolia",
		networkType: "testnet",
		explorerUrl: "https://sepolia.etherscan.io",
		rddUrl: "https://reference-data-directory.vercel.app/feeds-ethereum-testnet-sepolia.json",
		rpcUrl: {
			alchemy: "https://eth-sepolia.g.alchemy.com/v2/",
			infura: "https://sepolia.infura.io/v3/",
		},
	},
	{
		chainId: ChainId.OPTIMISM,
		chainAlias: "optimism",
		name: "Optimism",
		networkType: "mainnet",
		explorerUrl: "https://optimistic.etherscan.io",
		rddUrl: "https://reference-data-directory.vercel.app/feeds-ethereum-mainnet-optimism-1.json",
		rpcUrl: {
			alchemy: "https://opt-mainnet.g.alchemy.com/v2/",
			infura: "https://optimism-mainnet.infura.io/v3/",
		},
	},
	{
		chainId: ChainId.OPTIMISM_SEPOLIA,
		chainAlias: "optimism-sepolia",
		name: "Optimism Sepolia",
		networkType: "testnet",
		explorerUrl: "https://sepolia-optimistic.etherscan.io",
		rddUrl: "https://reference-data-directory.vercel.app/feeds-ethereum-testnet-sepolia-optimism-1.json",
		rpcUrl: {
			alchemy: "https://opt-sepolia.g.alchemy.com/v2/",
			infura: "https://optimism-sepolia.infura.io/v3/",
		},
	},
	{
		chainId: ChainId.BNB,
		chainAlias: "bnb",
		name: "BNB",
		networkType: "mainnet",
		explorerUrl: "https://bscscan.com",
		rddUrl: "https://reference-data-directory.vercel.app/feeds-bsc-mainnet.json",
		rpcUrl: {
			alchemy: "https://bnb-mainnet.g.alchemy.com/v2/",
			infura: "https://bsc-mainnet.infura.io/v3/",
		},
	},
	{
		chainId: ChainId.BNB_TESTNET,
		chainAlias: "bnb-testnet",
		name: "BNB Testnet",
		networkType: "testnet",
		explorerUrl: "https://testnet.bscscan.com",
		rddUrl: "https://reference-data-directory.vercel.app/feeds-bsc-testnet.json",
		rpcUrl: {
			alchemy: "https://bnb-testnet.g.alchemy.com/v2/",
			infura: "https://bsc-testnet.infura.io/v3/",
		},
	},
	{
		chainId: ChainId.UNICHAIN,
		chainAlias: "unichain",
		name: "Unichain",
		networkType: "mainnet",
		explorerUrl: "https://uniscan.xyz",
		rddUrl: "",
		rpcUrl: {
			alchemy: "https://unichain-mainnet.g.alchemy.com/v2/",
			infura: "https://unichain-mainnet.infura.io/v3/",
		},
	},
	{
		chainId: ChainId.UNICHAIN_SEPOLIA,
		chainAlias: "unichain-sepolia",
		name: "Unichain Sepolia",
		networkType: "testnet",
		explorerUrl: "https://sepolia.uniscan.xyz",
		rddUrl: "https://reference-data-directory.vercel.app/feeds-ethereum-testnet-sepolia-unichain-1.json",
		rpcUrl: {
			alchemy: "https://unichain-sepolia.g.alchemy.com/v2/",
			infura: "https://unichain-sepolia.infura.io/v3/",
		},
	},
	{
		chainId: ChainId.POLYGON,
		chainAlias: "polygon",
		name: "Polygon",
		networkType: "mainnet",
		explorerUrl: "https://polygonscan.com",
		rddUrl: "https://reference-data-directory.vercel.app/feeds-matic-mainnet.json",
		rpcUrl: {
			alchemy: "https://polygon-mainnet.g.alchemy.com/v2/",
			infura: "https://polygon-mainnet.infura.io/v3/",
		},
	},
	{
		chainId: ChainId.POLYGON_AMOY,
		chainAlias: "polygon-amoy",
		name: "Polygon Amoy",
		networkType: "testnet",
		explorerUrl: "https://amoy.polygonscan.com",
		rddUrl: "https://reference-data-directory.vercel.app/feeds-polygon-testnet-amoy.json",
		rpcUrl: {
			alchemy: "https://polygon-amoy.g.alchemy.com/v2/",
			infura: "https://polygon-amoy.infura.io/v3/",
		},
	},
	{
		chainId: ChainId.BASE,
		chainAlias: "base",
		name: "Base",
		networkType: "mainnet",
		explorerUrl: "https://basescan.org",
		rddUrl: "https://reference-data-directory.vercel.app/feeds-ethereum-mainnet-base-1.json",
		rpcUrl: {
			alchemy: "https://base-mainnet.g.alchemy.com/v2/",
			infura: "https://base-mainnet.infura.io/v3/",
		},
	},
	{
		chainId: ChainId.BASE_SEPOLIA,
		chainAlias: "base-sepolia",
		name: "Base Sepolia",
		networkType: "testnet",
		explorerUrl: "https://sepolia.basescan.org",
		rddUrl: "https://reference-data-directory.vercel.app/feeds-ethereum-testnet-sepolia-base-1.json",
		rpcUrl: {
			alchemy: "https://base-sepolia.g.alchemy.com/v2/",
			infura: "https://base-sepolia.infura.io/v3/",
		},
	},
	{
		chainId: ChainId.ARBITRUM,
		chainAlias: "arbitrum",
		name: "Arbitrum One",
		networkType: "mainnet",
		explorerUrl: "https://arbiscan.io",
		rddUrl: "https://reference-data-directory.vercel.app/feeds-ethereum-mainnet-arbitrum-1.json",
		rpcUrl: {
			alchemy: "https://arb-mainnet.g.alchemy.com/v2/",
			infura: "https://arbitrum-mainnet.infura.io/v3/",
		},
	},
	{
		chainId: ChainId.ARBITRUM_SEPOLIA,
		chainAlias: "arbitrum-sepolia",
		name: "Arbitrum One Sepolia",
		networkType: "testnet",
		explorerUrl: "https://sepolia.arbiscan.io",
		rddUrl: "https://reference-data-directory.vercel.app/feeds-ethereum-testnet-sepolia-arbitrum-1.json",
		rpcUrl: {
			alchemy: "https://arb-sepolia.g.alchemy.com/v2/",
			infura: "https://arbitrum-sepolia.infura.io/v3/",
		},
	},
	{
		chainId: ChainId.AVALANCHE,
		chainAlias: "avalanche",
		name: "Avalanche",
		networkType: "mainnet",
		explorerUrl: "https://snowtrace.io",
		rddUrl: "https://reference-data-directory.vercel.app/feeds-avalanche-mainnet.json",
		rpcUrl: {
			alchemy: "https://avax-mainnet.g.alchemy.com/v2/",
			infura: "https://avalanche-mainnet.infura.io/v3/",
		},
	},
	{
		chainId: ChainId.AVALANCHE_FUJI,
		chainAlias: "avalanche-fuji",
		name: "Avalanche Fuji",
		networkType: "testnet",
		explorerUrl: "https://testnet.snowtrace.io",
		rddUrl: "https://reference-data-directory.vercel.app/feeds-avalanche-fuji-testnet.json",
		rpcUrl: {
			alchemy: "https://avax-fuji.g.alchemy.com/v2/",
			infura: "https://avalanche-fuji.infura.io/v3/",
		},
	},
	{
		chainId: ChainId.LINEA,
		chainAlias: "linea",
		name: "Linea",
		networkType: "mainnet",
		explorerUrl: "https://lineascan.build",
		rddUrl: "https://reference-data-directory.vercel.app/feeds-ethereum-mainnet-linea-1.json",
		rpcUrl: {
			alchemy: "https://linea-mainnet.g.alchemy.com/v2/",
			infura: "https://linea-mainnet.infura.io/v3/",
		},
	},
	{
		chainId: ChainId.LINEA,
		chainAlias: "linea",
		name: "Linea Sepolia",
		networkType: "testnet",
		explorerUrl: "https://sepolia.lineascan.build",
		rddUrl: "",
		rpcUrl: {
			alchemy: "https://linea-sepolia.g.alchemy.com/v2/",
			infura: "https://linea-sepolia.infura.io/v3/",
		},
	},
	{
		chainId: ChainId.SCROLL,
		chainAlias: "scroll",
		name: "Scroll",
		networkType: "mainnet",
		explorerUrl: "https://scrollscan.com",
		rddUrl: "https://reference-data-directory.vercel.app/feeds-ethereum-mainnet-scroll-1.json",
		rpcUrl: {
			alchemy: "https://scroll-mainnet.g.alchemy.com/v2/",
			infura: "https://scroll-mainnet.infura.io/v3/",
		},
	},
	{
		chainId: ChainId.SCROLL_SEPOLIA,
		chainAlias: "scroll-sepolia",
		name: "Scroll Sepolia",
		networkType: "testnet",
		explorerUrl: "https://sepolia.scrollscan.com",
		rddUrl: "https://reference-data-directory.vercel.app/feeds-ethereum-testnet-sepolia-scroll-1.json",
		rpcUrl: {
			alchemy: "https://scroll-sepolia.g.alchemy.com/v2/",
			infura: "https://scroll-sepolia.infura.io/v3/",
		},
	},
];

export const ERC1967_ADMIN_SLOT = "0xb53127684a568b3173ae13b9f8a6016e243e63b6e8ee1178d6a717850b5d6103";

export const ERC1967_IMPLEMENTATION_SLOT = "0x360894a13ba1a3210667c828492db98dca3e2076cc3735a920a3ca505d382bbc";
